CREATE TABLE IF NOT EXISTS Products(
    idProduct   INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        text    NOT NULL CHECK (name <> ''),
    description text,
    stock       INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Sales(
    idSale      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    idProduct   INTEGER REFERENCES Products(idProduct),
    datePurchase DATE   NOT NULL
);


INSERT INTO	PRODUCTS (name, description, stock) VALUES('Televisor',	'Samsung',	10);
INSERT INTO	PRODUCTS (name, description, stock) VALUES('Celular',	'Samsung',	12);
INSERT INTO	PRODUCTS (name, description, stock) VALUES('Nevera',	'LG',	25);
INSERT INTO	PRODUCTS (name, description, stock) VALUES('Lavadora',	'MABE',	30);



INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(1, '2021-09-02');

INSERT INTO SALES (idProduct, datepurchase) VALUES(2, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(2, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(2, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(2, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(2, '2021-09-02');

INSERT INTO SALES (idProduct, datepurchase) VALUES(3, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(3, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(3, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(3, '2021-09-02');

INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-01');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-02');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');
INSERT INTO SALES (idProduct, datepurchase) VALUES(4, '2021-09-03');